<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>lol.pyr</groupId>
        <artifactId>znpcsplus-parent</artifactId>
        <version>2.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>znpcsplus-plugin</artifactId>
    <name>znpcsplus-plugin</name>

    <dependencies>
        <dependency>
            <groupId>lol.pyr</groupId>
            <artifactId>znpcsplus-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.7</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.retrooper</groupId>
            <artifactId>packetevents-spigot</artifactId>
            <version>2.11.1</version>
        </dependency>
        <dependency>
            <groupId>space.arim.dazzleconf</groupId>
            <artifactId>dazzleconf-ext-snakeyaml</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.28</version>
        </dependency>
        <dependency>
            <groupId>lol.pyr</groupId>
            <artifactId>director-adventure</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bukkit</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-minimessage</artifactId>
            <version>4.25.0</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>ZNPCsPlus</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>plugin.yml</exclude>
                </excludes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <shadedArtifactAttached>false</shadedArtifactAttached>

                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Git-Branch>${env.GIT_BRANCH}</Git-Branch>
                                        <Git-Commit>${env.GIT_COMMIT}</Git-Commit>
                                        <Build-Id>${env.BUILD_ID}</Build-Id>
                                    </manifestEntries>
                                </transformer>
                            </transformers>

                            <relocations>
                                <relocation>
                                    <pattern>org.objectweb.asm</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.asm</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>me.lucko.jarrelocator</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.jarrelocator</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.bstats</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.kyori</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.kyori</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.checkerframework</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.checkerframework</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.gson</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.gson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.github.retrooper.packetevents</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.packetevents.api</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.github.retrooper.packetevents</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.packetevents.impl</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.yaml.snakeyaml</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.snakeyaml</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>space.arim.dazzleconf</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.dazzleconf</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>lol.pyr.director</pattern>
                                    <shadedPattern>lol.pyr.znpcsplus.libraries.command</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
